# ====================================
# FILE: config.py (v3.0 - Final)
# ====================================

# --- TELEGRAM CONFIGURATION ---
TELEGRAM_BOT_TOKEN = "7673207599:AAGieVWYvOl34OB0Lth8_Bsszw2fUTOw7rc"
TELEGRAM_CHAT_ID = "1950722362"

# --- AUTOMATION & API SETTINGS ---
SCAN_INTERVAL_HOURS = 4
API_TIMEOUT = 15
MAX_WORKERS = 10

# --- DYNAMIC LIQUIDITY FILTERS ---
STRICT_MIN_VOLUME_24H = 50_000_000
STRICT_MIN_OPEN_INTEREST = 50_000_000
RELAXED_MIN_VOLUME_24H = 20_000_000  # ปรับลดลงเล็กน้อย
RELAXED_MIN_OPEN_INTEREST = 20_000_000 # ปรับลดลงเล็กน้อย

# --- [ใหม่] DYNAMIC HEALTH SCORE THRESHOLDS ---
STRICT_MIN_HEALTH_SCORE = 50  # เกณฑ์คะแนนสำหรับตลาด Trending
RELAXED_MIN_HEALTH_SCORE = 35   # เกณฑ์คะแนนสำหรับตลาด Quiet/Choppy

# --- RANKING & REPORTING ---
TOP_BULLISH_COUNT = 10
TOP_BEARISH_COUNT = 10

# --- TECHNICAL ANALYSIS PARAMETERS ---
TIMEFRAME = "240"
KLINE_LIMIT = 250
EMA_SHORT_PERIOD = 50
EMA_LONG_PERIOD = 200
ATR_PERIOD = 14

# --- MARKET REGIME THRESHOLDS (ATR %) ---
ATR_TRENDING_THRESHOLD = 2.5
ATR_QUIET_THRESHOLD = 1.2 # ปรับขึ้นเล็กน้อยเพื่อจับสภาวะ Ranging ได้ดีขึ้น

# --- TREND STAGE / OVEREXTENDED THRESHOLDS ---
MAX_DISTANCE_FROM_EMA_PERCENT = 15.0
EARLY_STAGE_MAX_PERCENT = 5.0
MID_STAGE_MAX_PERCENT = 15.0

# --- LOGGING CONFIGURATION ---
LOG_LEVEL = "INFO"
LOG_FILE = "market_intelligence.log"
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'